### ISSUE TITLE
Editing on iOS

### ISSUE THREAD

**Issue by suryamalempati** [swastik/ember-inline-edit#13]
The application I'm using ember-inline-edit works fine with the Chrome Browser on Android, but the same does not work with Chrome Browser(Or Safari) on iOS. 
startEditing action is not being called on a touch action. 
Is there something we'll have to add/modify in order to get it working on a browser running on iOS?
Inserting the code from the template where I'm using ember-inline-edit

`{{ember-inline-edit value=<model>.<attr> onSave = (action "updateModel" <model>.id) onClose = (action "rollbackModel" <model>.id)}}`

**Comment by swastik** [comment]
Thanks for reporting, @suryamalempati!

I don't think this has touch support yet. I do have plans to it though. I'll look into it this weekend.

**Comment by suryamalempati** [comment]
Oh. Okay. 

Thank you

**Comment by swastik** [comment]
Got some time and took a shot at it. It turned out simply adding a `cursor: pointer` to the element did the trick. I also experimented with `touchstart` but it created more problems — a user could accidentally click on the element while scrolling.

It's on the master branch. Let me know if you can try installing from master and if it works. I'll publish a release.

Thanks again for reporting this. 😄

**Comment by swastik** [comment]
@suryamalempati 

Got some time and took a shot at it. It turned out simply adding a `cursor: pointer` to the element did the trick. I also experimented with `touchstart` but it created more problems — a user could accidentally click on the element while scrolling.

It's on the master branch. Let me know if you can try installing from master and if it works. I'll publish a release.

Thanks again for reporting this. 😄

**Comment by suryamalempati** [comment]
Yup. Just tested it out and we're able to edit now. But we're not able to mimic the ESC key by touching outside the field. 
We'll have to click on another clickable element for onClose to be invoked. But the field is now editable on touch.

**Comment by swastik** [comment]
Good point! I'll look into possible solutions for that.
