### ISSUE TITLE
Quick noobie question

### ISSUE THREAD

**Issue by amclelland** [swastik/ember-inline-edit#9]
I followed the instruction in the readme but I'm having trouble saving the edited text.

In my `routes/meals/show.js` I have:

```
model(params) {
    return this.store.findRecord('meal', params.meal_id);
  },
actions: {
    changeName(val) {
      this.set('name', val);
    }
  }
```

but nothing happens at all. My backend doesn't get any messages. I know it's hitting the `changeName` function though, debugger works in it. This is in Ember 2.6 btw. Is there a step I am missing? Thanks!

**Comment by swastik** [comment]
Thanks for reporting! 😄 

Any idea what version are you using and what does your template look like?

**Comment by amclelland** [comment]
Looks like I'm using ember-inline-edit version 0.1.7

Here's my `/meals/show.hbs` template:
```
<div class="meal">
  <h1>{{ember-inline-edit value=model.name onSave='changeName'}}</h1>
  <img src={{model.image}} class="meal-image">

  <hr>

  <h2>Ingredients:</h2>
  {{#paper-button primary=true noink="true"}}New Ingredient{{/paper-button}}

  {{#each model.ingredients as |ingredient|}}
    <p>{{ingredient.name}}</p>
  {{/each}}
</div>
```

and here's the whole project in case it helps:
https://github.com/amclelland/fancy_recipme_frontend/tree/ingredients

Thanks for your help! :)

**Comment by swastik** [comment]
@amclelland — Got it! 😃 

I think the problem's what I mentioned in my comment above. Please try that change and see if it works.

Also, I see that you've commented out:

```
      // this.get('model').set('name', val);
      // this.set('name', val);
```

What ember does is, once the model is loaded, it sets the `model` property on the controller, not the route. So, if you try to access the model from the controller (like you've done on the first commented line above), it'll work just fine. But from the route, you should do:

```
      this.modelFor(this.routeName).set('name', val);
```

... and that should do it.

**Comment by amclelland** [comment]
Hey Swastik, that did it!! Thanks very much!! I did also have to call this afterward though:
`this.modelFor(this.routeName).save();`

So am I doing something wrong that I need to have a different way of saving the model? Should I have placed the `changeName` method on the controller instead? Sorry for the noob questions! :sweat_smile:

**Comment by swastik** [comment]
Awesome! No problems with the questions. 😃 

If you place these on the controller, they will work just fine, but you don't really need that. They will work from the route, too, as you just saw.

An easier way to do this (I'll update the documentation in a bit) would be:

```
{{ember-inline-edit value=model.name onSave=(action (mut model.name))}}
```

This will work only in Ember 2.0 (which isn't a problem since you're using 2.6). What this essentially says is when the `onSave` action is triggered, change the `model.name` property. It does the same thing that you're doing right now (through the action); it's just less code.

You're not doing anything wrong, by the way. This addon just sends a `onSave` action that tells you that the _value_ has changed; it's up to you what you want to do with it. It doesn't do more than that because that means it's flexible enough to do what you want it to do! 😄

**Comment by amclelland** [comment]
Very cool, thanks very much! :)
